name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install Maven (Linux)
      - uses: actions/checkout@v4
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  release-win:
    if: github.event_name == 'release'
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release-linux:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build release binary
      run: cargo build --release --verbose
    - name: Upload Linux x86_64 binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: ./target/release/lazymvn
        tag_name: ${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'release'
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Build release binary
      run: cargo build --release --verbose
    - name: Upload Windows x86_64 binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: ./target/release/lazymvn.exe
        tag_name: ${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
