name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install Maven (Linux)
      - uses: actions/checkout@v4
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  release-win:
    if: github.event_name == 'release'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    if: github.event_name == 'release'
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build release binary
      run: cargo build --release --verbose
    - name: Upload Windows x86_64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/lazymvn.exe
        asset_name: lazymvn-windows-x86_64.exe
        asset_content_type: application/octet-stream
